<a href="https://colab.research.google.com/github/somarathigaganasaisree/Certificates/blob/main/Week_2_MDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np

## NumPy Array Manipulation

### Indexing NumPy arrays

In [47]:
# Create a 1D array for indexing examples
a1 = np.array([112, 20, 30, 40, 50])
print(f"Original 1D array: {a1}")

Original 1D array: [112  20  30  40  50]


In [48]:
# Access element at index 0
print(f"Element at index 0: {a1[0]}")

Element at index 0: 112


In [49]:
# Access the last element using negative indexing
print(f"Last element: {a1[-1]}")

Last element: 50


In [50]:
# Create a 2D array for indexing examples
a2 = np.array([[112, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nOriginal 2D array:\n{a2}")


Original 2D array:
[[112   2   3]
 [  4   5   6]
 [  7   8   9]]


In [51]:
# Access element at row 0, column 1
print(f"Element at row 0, column 1: {a2[0, 1]}")

Element at row 0, column 1: 2


In [52]:
# Access the first row (all columns of the first row)
print(f"First row: {a2[0]}")

First row: [112   2   3]


### Slicing NumPy arrays

In [53]:
# Create a 1D array for slicing examples
s1 = np.array([112, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Original 1D array: {s1}")

Original 1D array: [112   2   3   4   5   6   7   8   9  10]


In [54]:
# Slice elements from index 2 to 5 (exclusive of 6)
print(f"Elements from index 2 to 5: {s1[2:6]}")

Elements from index 2 to 5: [3 4 5 6]


In [55]:
# Slice elements from the start to index 4 (exclusive of 5)
print(f"Elements from start to index 4: {s1[:5]}")

Elements from start to index 4: [112   2   3   4   5]


In [56]:
# Slice every other element
print(f"Every other element: {s1[::2]}")

Every other element: [112   3   5   7   9]


In [57]:
# Create a 2D array for slicing examples
s2 = np.array([
    [112, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])
print(f"\nOriginal 2D array:\n{s2}")


Original 2D array:
[[112  11  12  13]
 [ 14  15  16  17]
 [ 18  19  20  21]]


In [58]:
# Slice the first two rows, all columns
print(f"\nFirst two rows, all columns:\n{s2[0:2, :]}")


First two rows, all columns:
[[112  11  12  13]
 [ 14  15  16  17]]


In [59]:
# Slice all rows, columns 1 and 2 (exclusive of 3)
print(f"\nAll rows, columns 1 and 2:\n{s2[:, 1:3]}")


All rows, columns 1 and 2:
[[11 12]
 [15 16]
 [19 20]]


### Reshaping NumPy arrays

In [60]:
# Create a 1D array for reshaping examples
r_orig = np.arange(1, 10) # [1 2 3 4 5 6 7 8 9]
r_orig[0] = 112
print(f"Original 1D array: {r_orig}")

Original 1D array: [112   2   3   4   5   6   7   8   9]


In [61]:
# Print original shape
print(f"Original shape: {r_orig.shape}")

Original shape: (9,)


In [62]:
# Reshape to a 3x3 2D array
r_new = r_orig.reshape(3, 3)
print(f"\nReshaped to 3x3 array:\n{r_new}")


Reshaped to 3x3 array:
[[112   2   3]
 [  4   5   6]
 [  7   8   9]]


In [63]:
# Print new shape after reshaping
print(f"New shape: {r_new.shape}")

New shape: (3, 3)


In [64]:
# Flatten the 2D array back to a 1D array
r_flat = r_new.flatten()
print(f"\nFlattened array:\n{r_flat}")


Flattened array:
[112   2   3   4   5   6   7   8   9]


In [65]:
# Print new shape after flattening
print(f"New shape: {r_flat.shape}")

New shape: (9,)


### Joining NumPy arrays

In [66]:
# Create two 1D arrays for joining examples
j1_1d = np.array([112, 2, 3])
j2_1d = np.array([4, 5, 6])
print(f"Array 1 (1D): {j1_1d}")
print(f"Array 2 (1D): {j2_1d}")

Array 1 (1D): [112   2   3]
Array 2 (1D): [4 5 6]


In [67]:
# Concatenate 1D arrays (stacks them end-to-end)
j_1d_res = np.concatenate((j1_1d, j2_1d))
print(f"Joined 1D arrays: {j_1d_res}")

Joined 1D arrays: [112   2   3   4   5   6]


In [68]:
# Create two 2D arrays for joining examples
j1_2d = np.array([[112, 2], [3, 4]])
j2_2d = np.array([[5, 6], [7, 8]])
print(f"\nArray 1 (2D):\n{j1_2d}")
print(f"Array 2 (2D):\n{j2_2d}")


Array 1 (2D):
[[112   2]
 [  3   4]]
Array 2 (2D):
[[5 6]
 [7 8]]


In [69]:
# Join 2D arrays along rows (axis=0)
j_rows_res = np.concatenate((j1_2d, j2_2d), axis=0)
print(f"\nJoined along rows (axis=0):\n{j_rows_res}")


Joined along rows (axis=0):
[[112   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [70]:
# Join 2D arrays along columns (axis=1)
j_cols_res = np.concatenate((j1_2d, j2_2d), axis=1)
print(f"\nJoined along columns (axis=1):\n{j_cols_res}")


Joined along columns (axis=1):
[[112   2   5   6]
 [  3   4   7   8]]


### Splitting NumPy arrays

In [71]:
# Create a 1D array for splitting examples
sp1d_orig = np.array([112, 2, 3, 4, 5, 6])
print(f"Original 1D array: {sp1d_orig}")

Original 1D array: [112   2   3   4   5   6]


In [72]:
# Split the 1D array into 3 equal parts
sp1d_res = np.split(sp1d_orig, 3)
print(f"\nSplit into 3 equal parts: {sp1d_res}")


Split into 3 equal parts: [array([112,   2]), array([3, 4]), array([5, 6])]


In [73]:
# Create a 2D array for splitting examples
sp2d_orig = np.array([
    [112, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21],
    [22, 23, 24, 25]
])
print(f"\nOriginal 2D array:\n{sp2d_orig}")


Original 2D array:
[[112  11  12  13]
 [ 14  15  16  17]
 [ 18  19  20  21]
 [ 22  23  24  25]]


In [74]:
# Split the 2D array along rows (axis=0) into 2 equal parts
sp2d_rows_res = np.split(sp2d_orig, 2, axis=0)
print(f"\nSplit along rows (axis=0) into 2 parts:\nPart 1:\n{sp2d_rows_res[0]}\nPart 2:\n{sp2d_rows_res[1]}")


Split along rows (axis=0) into 2 parts:
Part 1:
[[112  11  12  13]
 [ 14  15  16  17]]
Part 2:
[[18 19 20 21]
 [22 23 24 25]]


In [75]:
# Split the 2D array along columns (axis=1) into 2 equal parts
sp2d_cols_res = np.split(sp2d_orig, 2, axis=1)
print(f"\nSplit along columns (axis=1) into 2 parts:\nPart 1:\n{sp2d_cols_res[0]}\nPart 2:\n{sp2d_cols_res[1]}")


Split along columns (axis=1) into 2 parts:
Part 1:
[[112  11]
 [ 14  15]
 [ 18  19]
 [ 22  23]]
Part 2:
[[12 13]
 [16 17]
 [20 21]
 [24 25]]


## NumPy Array Manipulation

In [76]:
# Indexing NumPy arrays
# Accessing elements using their position.

# Create a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])
print(f"Original 1D array: {arr_1d}")
print(f"Element at index 0: {arr_1d[0]}")
print(f"Last element: {arr_1d[-1]}")

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nOriginal 2D array:\n{arr_2d}")
print(f"Element at row 0, column 1: {arr_2d[0, 1]}")
print(f"First row: {arr_2d[0]}")

Original 1D array: [10 20 30 40 50]
Element at index 0: 10
Last element: 50

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, column 1: 2
First row: [1 2 3]


In [77]:
# Slicing NumPy arrays
# Extracting a portion of an array.

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Original 1D array: {arr_1d}")
print(f"Elements from index 2 to 5: {arr_1d[2:6]}")
print(f"Elements from start to index 4: {arr_1d[:5]}")
print(f"Every other element: {arr_1d[::2]}")

# Create a 2D array
arr_2d = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21]
])
print(f"\nOriginal 2D array:\n{arr_2d}")
print(f"\nFirst two rows, all columns:\n{arr_2d[0:2, :]}")
print(f"\nAll rows, columns 1 and 2:\n{arr_2d[:, 1:3]}")

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10]
Elements from index 2 to 5: [3 4 5 6]
Elements from start to index 4: [1 2 3 4 5]
Every other element: [1 3 5 7 9]

Original 2D array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

First two rows, all columns:
[[10 11 12 13]
 [14 15 16 17]]

All rows, columns 1 and 2:
[[11 12]
 [15 16]
 [19 20]]


In [78]:
# Reshaping NumPy arrays
# Changing the dimensions of an array without changing its data.

# Create a 1D array
arr = np.arange(1, 10) # [1 2 3 4 5 6 7 8 9]
print(f"Original 1D array: {arr}")
print(f"Original shape: {arr.shape}")

# Reshape to a 3x3 2D array
reshaped_arr = arr.reshape(3, 3)
print(f"\nReshaped to 3x3 array:\n{reshaped_arr}")
print(f"New shape: {reshaped_arr.shape}")

# Flatten back to a 1D array
flattened_arr = reshaped_arr.flatten()
print(f"\nFlattened array:\n{flattened_arr}")
print(f"New shape: {flattened_arr.shape}")

Original 1D array: [1 2 3 4 5 6 7 8 9]
Original shape: (9,)

Reshaped to 3x3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
New shape: (3, 3)

Flattened array:
[1 2 3 4 5 6 7 8 9]
New shape: (9,)


In [79]:
# Joining NumPy arrays
# Combining multiple arrays into a single array.

# Create two 1D arrays
arr1_1d = np.array([1, 2, 3])
arr2_1d = np.array([4, 5, 6])
print(f"Array 1 (1D): {arr1_1d}")
print(f"Array 2 (1D): {arr2_1d}")

# Concatenate 1D arrays (stacks them)
joined_1d = np.concatenate((arr1_1d, arr2_1d))
print(f"Joined 1D arrays: {joined_1d}")

# Create two 2D arrays
arr1_2d = np.array([[1, 2], [3, 4]])
arr2_2d = np.array([[5, 6], [7, 8]])
print(f"\nArray 1 (2D):\n{arr1_2d}")
print(f"Array 2 (2D):\n{arr2_2d}")

# Join along rows (axis=0)
joined_rows = np.concatenate((arr1_2d, arr2_2d), axis=0)
print(f"\nJoined along rows (axis=0):\n{joined_rows}")

# Join along columns (axis=1)
joined_cols = np.concatenate((arr1_2d, arr2_2d), axis=1)
print(f"\nJoined along columns (axis=1):\n{joined_cols}")

Array 1 (1D): [1 2 3]
Array 2 (1D): [4 5 6]
Joined 1D arrays: [1 2 3 4 5 6]

Array 1 (2D):
[[1 2]
 [3 4]]
Array 2 (2D):
[[5 6]
 [7 8]]

Joined along rows (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Joined along columns (axis=1):
[[1 2 5 6]
 [3 4 7 8]]


In [80]:
# Splitting NumPy arrays
# Dividing a single array into multiple smaller arrays.

# Create a 1D array
arr_to_split_1d = np.array([1, 2, 3, 4, 5, 6])
print(f"Original 1D array: {arr_to_split_1d}")

# Split into 3 equal parts
split_1d_equal = np.split(arr_to_split_1d, 3)
print(f"\nSplit into 3 equal parts: {split_1d_equal}")

# Create a 2D array
arr_to_split_2d = np.array([
    [10, 11, 12, 13],
    [14, 15, 16, 17],
    [18, 19, 20, 21],
    [22, 23, 24, 25]
])
print(f"\nOriginal 2D array:\n{arr_to_split_2d}")

# Split along rows (axis=0) into 2 equal parts
split_2d_rows = np.split(arr_to_split_2d, 2, axis=0)
print(f"\nSplit along rows (axis=0) into 2 parts:\nPart 1:\n{split_2d_rows[0]}\nPart 2:\n{split_2d_rows[1]}")

# Split along columns (axis=1) into 2 equal parts
split_2d_cols = np.split(arr_to_split_2d, 2, axis=1)
print(f"\nSplit along columns (axis=1) into 2 parts:\nPart 1:\n{split_2d_cols[0]}\nPart 2:\n{split_2d_cols[1]}")

Original 1D array: [1 2 3 4 5 6]

Split into 3 equal parts: [array([1, 2]), array([3, 4]), array([5, 6])]

Original 2D array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]

Split along rows (axis=0) into 2 parts:
Part 1:
[[10 11 12 13]
 [14 15 16 17]]
Part 2:
[[18 19 20 21]
 [22 23 24 25]]

Split along columns (axis=1) into 2 parts:
Part 1:
[[10 11]
 [14 15]
 [18 19]
 [22 23]]
Part 2:
[[12 13]
 [16 17]
 [20 21]
 [24 25]]
