<a href="https://colab.research.google.com/github/somarathigaganasaisree/Certificates/blob/main/Week_1_MDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install the numpy library
!pip install numpy

In [2]:
# Import the numpy library and print its version
import numpy as np
print(np.__version__)

2.0.2


In [3]:
import time
import numpy as np

# Define the size of the collections for performance comparison
size = 10**6 # One million elements

# --- Python List Performance ---
# Measure time taken for element-wise addition using Python lists
start_time_list = time.time()
list1 = list(range(size))
list2 = list(range(size))
result_list = [list1[i] + list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken by Python lists: {time_list:.6f} seconds")

# --- NumPy Array Performance ---
# Measure time taken for element-wise addition using NumPy arrays
start_time_numpy = time.time()
numpy_array1 = np.arange(size)
numpy_array2 = np.arange(size)
result_numpy = numpy_array1 + numpy_array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken by NumPy arrays: {time_numpy:.6f} seconds")

# Compare performance
print(f"\nNumPy is approximately {time_list / time_numpy:.2f} times faster than Python lists for this operation.")

Time taken by Python lists: 0.150898 seconds
Time taken by NumPy arrays: 0.008597 seconds

NumPy is approximately 17.55 times faster than Python lists for this operation.


In [4]:
import sys
import numpy as np

# Define the size of the collections for memory comparison
size = 10**6 # One million elements

# --- Python List Memory Usage ---
# Get the memory size of a Python list of integers
list_memory = sys.getsizeof(list(range(size)))
print(f"Memory taken by Python list (for {size} integers): {list_memory} bytes")

# --- NumPy Array Memory Usage ---
# Get the memory size of a NumPy array of integers
numpy_array_memory = np.arange(size).nbytes
print(f"Memory taken by NumPy array (for {size} integers): {numpy_array_memory} bytes")

# Compare memory usage
print(f"\nPython list uses approximately {list_memory / numpy_array_memory:.2f} times more memory than NumPy array for this data type and size.")

Memory taken by Python list (for 1000000 integers): 8000056 bytes
Memory taken by NumPy array (for 1000000 integers): 8000000 bytes

Python list uses approximately 1.00 times more memory than NumPy array for this data type and size.


In [88]:
# Create a Python list
list=[112,2,3,4,5]

In [89]:
# Print the type of the 'list' variable
print(type(list))

<class 'list'>


In [90]:
# Convert a Python list to a NumPy array and print it
a1=np.array(list)
print(a1)

[112   2   3   4   5]


In [12]:
# Print the type of the NumPy array 'a1'
print(type(a1))

<class 'numpy.ndarray'>


In [14]:
# Display the data type of elements in array 'a1'
a1.dtype

dtype('int64')

In [16]:
# Display the name of the data type of elements in array 'a1'
a1.dtype.name

'int64'

In [17]:
# Display the total number of elements in array 'a1'
a1.size

5

In [18]:
# Display the dimensions (shape) of array 'a1'
a1.shape

(5,)

In [19]:
# Display the total number of bytes consumed by the elements of array 'a1'
a1.nbytes

40

In [91]:
# Create a Python tuple
tuple=(112,2,3,4,5)

In [92]:
# Print the type of the 'tuple' variable
type(tuple)

tuple

In [93]:
# Create another Python tuple with a single element
tuple2=(1,)

In [29]:
# Print the type of the 'tuple2' variable
type(tuple2)

tuple

In [94]:
# Convert a Python tuple to a NumPy array and print it
a2=np.array(tuple)
print(a2)

[112   2   3   4   5]


In [31]:
# Display the total number of elements in array 'a2'
a2.size

5

In [95]:
# Create a 2D Python list and convert it to a NumPy matrix (2D array)
list3=[[112,2],[3,4]]
matrix=np.array(list3)

In [96]:
# Print the created NumPy matrix
print(matrix)

[[112   2]
 [  3   4]]


In [40]:
# Display the number of dimensions of the 'matrix'
matrix.ndim

2

In [42]:
# Display the dimensions (shape) of the 'matrix'
matrix.shape

(2, 2)

In [43]:
# Display the total number of elements in the 'matrix'
matrix.size

4

In [45]:
# Display the total number of bytes consumed by the elements of 'matrix'
matrix.nbytes

32

In [97]:
# Flatten the 'matrix' into a 1D array (returns a copy)
matrix.flatten()

array([112,   2,   3,   4])

In [98]:
# Flatten the 'matrix' into a 1D array (returns a view where possible)
matrix.ravel()

array([112,   2,   3,   4])

In [99]:
# Create a 1-dimensional NumPy array directly
a4=np.array([112,2,3,4])

In [100]:
# Print the 1-dimensional array 'a4'
print(a4)

[112   2   3   4]


In [101]:
# Create a 2-dimensional NumPy array directly
arr5=np.array([[112,2],[3,4]])

In [102]:
# Print the 2-dimensional array 'arr5'
print(arr5)

[[112   2]
 [  3   4]]


In [103]:
# Create a NumPy matrix (2D array) using np.matrix
arr6=np.matrix([[112,2],[3,4],[5,6]])

In [104]:
# Print the NumPy matrix 'arr6'
print(arr6)

[[112   2]
 [  3   4]
 [  5   6]]


In [55]:
import numpy as np

# Create a 1-dimensional array with 100 elements from 1 to 100 using np.arange
array_100_elements = np.arange(1, 101)

print("1-D Array with 100 elements:")
print(array_100_elements)

print("\nShape of the array:")
print(array_100_elements.shape)
print("Size of the array:")
print(array_100_elements.size)

1-D Array with 100 elements:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Shape of the array:
(100,)
Size of the array:
100


In [59]:
# Create an array of even numbers from 0 to 100 (inclusive) using np.arange with a step of 2
arr6=np.arange(0,101,2)
print(arr6)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [66]:
# Create a 2x5 matrix with elements from 0 to 9 using np.arange and reshape
matrix2=np.arange(0,10).reshape(2,5)

In [67]:
# Print the 2x5 matrix
print(matrix2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [69]:
# Create a 4x4 matrix filled with zeros (default float type)
zero_matrix = np.zeros((4, 4))
print("4x4 Zero Matrix:")
print(zero_matrix)

4x4 Zero Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [71]:
# Create a 3x3 integer matrix filled with zeros
a=np.zeros((3,3),dtype='int')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [72]:
# Create a 3x3 integer matrix filled with ones
a=np.ones((3,3),dtype='int')
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [75]:
# Create a 3x3 matrix filled with the value 2
c=np.full((3,3),2)
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [76]:
# Create another 3x3 matrix filled with the value 2 using np.full
d = np.full((3, 3), 2)
print("Identical matrix d:")
print(d)

Identical matrix d:
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [78]:
# Create a 3x3 identity matrix (diagonal matrix with ones on the main diagonal) with integer type
d=np.eye((3),dtype='int')
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [105]:
# Create an array with 5 evenly spaced numbers between 112 and 113 (inclusive)
e=np.linspace(112,113,5)
print(e)

[112.   112.25 112.5  112.75 113.  ]


In [81]:
# Create a 3x3 matrix with random numbers between 0 and 1
f=np.random.random((3,3))
print(f)

[[0.89291658 0.74058633 0.95374439]
 [0.4625982  0.39237956 0.76510756]
 [0.03587604 0.00830235 0.63137635]]


In [108]:
# Create a 1-D array with numbers from 112 up to (but not including) 121
arr1=np.arange(112,121)
print(arr1)

[112 113 114 115 116 117 118 119 120]


In [109]:
# Replace occurrences of the value 112 in 'arr1' with 111
arr1[arr1 == 112] = 111
print(arr1)

[111 113 114 115 116 117 118 119 120]


In [84]:
# Attempt to replace numerical values with a string 'csd' in 'arr1' (this will cause a ValueError if the array is of integer type)
arr1[arr1==111]='csd'
print(arr1)

ValueError: invalid literal for int() with base 10: 'csd'

In [111]:
# Corrected way to modify elements where arr1 is 112, 113, or 114
# Select elements that are equal to 112 OR 113 OR 114 using boolean indexing
condition = (arr1 == 112) |(arr1==113)|(arr1 == 114)

# Apply the multiplication only to the elements that satisfy the condition
arr1[condition] = arr1[condition] * 111

print(arr1)

[  111 12543 12654   115   116   117   118   119   120]


In [112]:
# Display the maximum value in the array 'arr1'
arr1.max()

np.int64(12654)