<a href="https://colab.research.google.com/github/somarathigaganasaisree/Certificates/blob/main/Week_1_MDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np
print(np.__version__)

2.0.2


In [3]:
import time
import numpy as np

# Define the size of the collections
size = 10**6 # One million elements

# --- Python List Performance ---
start_time_list = time.time()
list1 = list(range(size))
list2 = list(range(size))
result_list = [list1[i] + list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken by Python lists: {time_list:.6f} seconds")

# --- NumPy Array Performance ---
start_time_numpy = time.time()
numpy_array1 = np.arange(size)
numpy_array2 = np.arange(size)
result_numpy = numpy_array1 + numpy_array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken by NumPy arrays: {time_numpy:.6f} seconds")

print(f"\nNumPy is approximately {time_list / time_numpy:.2f} times faster than Python lists for this operation.")

Time taken by Python lists: 0.150898 seconds
Time taken by NumPy arrays: 0.008597 seconds

NumPy is approximately 17.55 times faster than Python lists for this operation.


In [4]:
import sys
import numpy as np

# Define the size of the collections
size = 10**6 # One million elements

# --- Python List Memory Usage ---
list_memory = sys.getsizeof(list(range(size)))
print(f"Memory taken by Python list (for {size} integers): {list_memory} bytes")

# --- NumPy Array Memory Usage ---
numpy_array_memory = np.arange(size).nbytes
print(f"Memory taken by NumPy array (for {size} integers): {numpy_array_memory} bytes")

print(f"\nPython list uses approximately {list_memory / numpy_array_memory:.2f} times more memory than NumPy array for this data type and size.")

Memory taken by Python list (for 1000000 integers): 8000056 bytes
Memory taken by NumPy array (for 1000000 integers): 8000000 bytes

Python list uses approximately 1.00 times more memory than NumPy array for this data type and size.


In [5]:
list=[1,2,3,4,5]

In [13]:
print(type(list))

<class 'list'>


In [11]:
a1=np.array(list)
print(a1)

[1 2 3 4 5]


In [12]:
print(type(a1))

<class 'numpy.ndarray'>


In [14]:
a1.dtype

dtype('int64')

In [16]:
a1.dtype.name

'int64'

In [17]:
a1.size

5

In [18]:
a1.shape

(5,)

In [19]:
a1.nbytes

40

In [21]:
tuple=(1,2,3,4,5)

In [22]:
type(tuple)

tuple

In [28]:
tuple2=(1,)

In [29]:
type(tuple2)

tuple

In [30]:
a2=np.array(tuple)
print(a2)

[1 2 3 4 5]


In [31]:
a2.size

5

In [33]:
import numpy as np

# Create a 2-dimensional array
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("2D Array:")
print(my_2d_array)

print("\nShape of the 2D array:")
print(my_2d_array.shape)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of the 2D array:
(3, 3)


In [38]:
list3=[[1,2],[3,4]]
matrix=np.array(list3)

In [39]:
print(matrix)

[[1 2]
 [3 4]]


In [40]:
matrix.ndim

2

In [42]:
matrix.shape

(2, 2)

In [43]:
matrix.size

4

In [45]:
matrix.nbytes

32

In [46]:
matrix.flatten()

array([1, 2, 3, 4])

In [47]:
matrix.ravel()

array([1, 2, 3, 4])

In [48]:
a4=np.array([1,2,3,4])

In [49]:
print(a4)

[1 2 3 4]


In [50]:
arr5=np.array([[1,2],[3,4]])

In [51]:
print(arr5)

[[1 2]
 [3 4]]


In [53]:
arr6=np.matrix([[1,2],[3,4],[5,6]])

In [54]:
print(arr6)

[[1 2]
 [3 4]
 [5 6]]


In [55]:
import numpy as np

# Create a 1-dimensional array with 100 elements from 1 to 100
array_100_elements = np.arange(1, 101)

print("1-D Array with 100 elements:")
print(array_100_elements)

print("\nShape of the array:")
print(array_100_elements.shape)
print("Size of the array:")
print(array_100_elements.size)

1-D Array with 100 elements:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Shape of the array:
(100,)
Size of the array:
100


In [59]:
arr6=np.arange(0,101,2)
print(arr6)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [61]:
temp_arr = np.arange(101) # Defaults to start=0, step=1
arr7 = temp_arr[temp_arr % 2 == 0]
print(arr7)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [66]:
matrix2=np.arange(0,10).reshape(2,5)

In [67]:
print(matrix2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [69]:
zero_matrix = np.zeros((4, 4))
print("4x4 Zero Matrix:")
print(zero_matrix)

4x4 Zero Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [71]:
a=np.zeros((3,3),dtype='int')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [72]:
a=np.ones((3,3),dtype='int')
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [75]:
c=np.full((3,3),2)
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [76]:
d = np.full((3, 3), 2)
print("Identical matrix d:")
print(d)

Identical matrix d:
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [77]:
diagonal_elements = np.array([1, 2, 3])
diagonal_matrix = np.diag(diagonal_elements)
print("Diagonal Matrix:")
print(diagonal_matrix)

Diagonal Matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [78]:
d=np.eye((3),dtype='int')
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [79]:
e=np.linspace(0,1,5)
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [81]:
f=np.random.random((3,3))
print(f)

[[0.89291658 0.74058633 0.95374439]
 [0.4625982  0.39237956 0.76510756]
 [0.03587604 0.00830235 0.63137635]]


In [82]:
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [83]:
arr1[arr1 == 1] = 111
print(arr1)

[111   2   3   4   5   6   7   8   9]


In [84]:
arr1[arr1==111]='csd'
print(arr1)

ValueError: invalid literal for int() with base 10: 'csd'

In [85]:
arr1[np.arange(arr1==3,arr1==5)]=arr1*111
print(arr1)

TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

In [86]:
# Corrected way to modify elements where arr1 is 3 or 5
# Select elements that are equal to 3 OR 5 using boolean indexing
condition = (arr1 == 3) | (arr1 == 5)

# Apply the multiplication only to the elements that satisfy the condition
arr1[condition] = arr1[condition] * 111

print(arr1)

[111   2 333   4 555   6   7   8   9]


In [87]:
arr1.max()

np.int64(555)

In [ ]:
np from string ,sets and dictionary