<a href="https://colab.research.google.com/github/somarathigaganasaisree/Certificates/blob/main/Week_1_MDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
# Install numpy
!pip install numpy

In [114]:
# Import numpy and print version
import numpy as np
print(np.__version__)

2.0.2


In [163]:
import time
import numpy as np

# Set size for performance comparison
size = 10**6

# Python List Performance (element-wise addition)
start_time_list = time.time()
list1 = list(range(size))
list2 = list(range(size))
result_list = [list1[i] + list2[i] for i in range(size)]
end_time_list = time.time()
time_list = end_time_list - start_time_list
print(f"Time taken by Python lists: {time_list:.6f} seconds")

# NumPy Array Performance (element-wise addition)
start_time_numpy = time.time()
numpy_array1 = np.arange(size)
numpy_array2 = np.arange(size)
result_numpy = numpy_array1 + numpy_array2
end_time_numpy = time.time()
time_numpy = end_time_numpy - start_time_numpy
print(f"Time taken by NumPy arrays: {time_numpy:.6f} seconds")

# Compare performance
print(f"\nNumPy is approximately {time_list / time_numpy:.2f} times faster than Python lists for this operation.")

TypeError: 'list' object is not callable

In [116]:
import sys
import numpy as np

# Set size for memory comparison
size = 10**6

# Python List Memory Usage
list_memory = sys.getsizeof(list(range(size)))
print(f"Memory taken by Python list (for {size} integers): {list_memory} bytes")

# NumPy Array Memory Usage
numpy_array_memory = np.arange(size).nbytes
print(f"Memory taken by NumPy array (for {size} integers): {numpy_array_memory} bytes")

# Compare memory usage
print(f"\nPython list uses approximately {list_memory / numpy_array_memory:.2f} times more memory than NumPy array for this data type and size.")

TypeError: 'list' object is not callable

In [117]:
# Create a Python list
my_list=[112,2,3,4,5]

In [118]:
# Print type of 'my_list'
print(type(my_list))

<class 'list'>


In [119]:
# Convert list to NumPy array and print
a1=np.array(my_list)
print(a1)

[112   2   3   4   5]


In [120]:
# Print type of NumPy array 'a1'
print(type(a1))

<class 'numpy.ndarray'>


In [121]:
# Display data type of elements in 'a1'
a1.dtype

dtype('int64')

In [122]:
# Display name of data type in 'a1'
a1.dtype.name

'int64'

In [123]:
# Display total elements in 'a1'
a1.size

5

In [124]:
# Display shape of 'a1'
a1.shape

(5,)

In [125]:
# Display bytes consumed by 'a1'
a1.nbytes

40

In [126]:
# Create a Python tuple
tuple=(112,2,3,4,5)

In [127]:
# Print type of 'tuple'
type(tuple)

tuple

In [128]:
# Create a single-element tuple
tuple2=(1,)

In [129]:
# Print type of 'tuple2'
type(tuple2)

tuple

In [130]:
# Convert tuple to NumPy array and print
a2=np.array(tuple)
print(a2)

[112   2   3   4   5]


In [131]:
# Display total elements in 'a2'
a2.size

5

In [132]:
# Create 2D list and convert to NumPy matrix
list3=[[112,2],[3,4]]
matrix=np.array(list3)

In [133]:
# Print NumPy matrix
print(matrix)

[[112   2]
 [  3   4]]


In [134]:
# Display number of dimensions of 'matrix'
matrix.ndim

2

In [135]:
# Display shape of 'matrix'
matrix.shape

(2, 2)

In [136]:
# Display total elements in 'matrix'
matrix.size

4

In [137]:
# Display bytes consumed by 'matrix'
matrix.nbytes

32

In [138]:
# Flatten 'matrix' (copy)
matrix.flatten()

array([112,   2,   3,   4])

In [139]:
# Flatten 'matrix' (view)
matrix.ravel()

array([112,   2,   3,   4])

In [140]:
# Create 1D NumPy array
a4=np.array([112,2,3,4])

In [141]:
# Print 1D array 'a4'
print(a4)

[112   2   3   4]


In [142]:
# Create 2D NumPy array
arr5=np.array([[112,2],[3,4]])

In [143]:
# Print 2D array 'arr5'
print(arr5)

[[112   2]
 [  3   4]]


In [144]:
# Create NumPy matrix 'arr6'
arr6=np.matrix([[112,2],[3,4],[5,6]])

In [145]:
# Print NumPy matrix 'arr6'
print(arr6)

[[112   2]
 [  3   4]
 [  5   6]]


In [146]:
import numpy as np

# Create 1D array with 100 elements (1 to 100)
array_100_elements = np.arange(1, 101)

print("1-D Array with 100 elements:")
print(array_100_elements)

print("\nShape of the array:")
print(array_100_elements.shape)
print("Size of the array:")
print(array_100_elements.size)

1-D Array with 100 elements:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Shape of the array:
(100,)
Size of the array:
100


In [147]:
# Create array of even numbers (0 to 100)
arr6=np.arange(0,101,2)
print(arr6)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [148]:
# Create 2x5 matrix from 0-9
matrix2=np.arange(0,10).reshape(2,5)

In [149]:
# Print 2x5 matrix
print(matrix2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [150]:
# Create 4x4 zero matrix
zero_matrix = np.zeros((4, 4))
print("4x4 Zero Matrix:")
print(zero_matrix)

4x4 Zero Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [151]:
# Create 3x3 integer zero matrix
a=np.zeros((3,3),dtype='int')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [152]:
# Create 3x3 integer one matrix
a=np.ones((3,3),dtype='int')
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [153]:
# Create 3x3 matrix filled with 2s
c=np.full((3,3),2)
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [154]:
# Create another 3x3 matrix filled with 2s
d = np.full((3, 3), 2)
print("Identical matrix d:")
print(d)

Identical matrix d:
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [155]:
# Create 3x3 integer identity matrix
d=np.eye((3),dtype='int')
print(d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [156]:
# Create 5 evenly spaced numbers between 112 and 113
e=np.linspace(112,113,5)
print(e)

[112.   112.25 112.5  112.75 113.  ]


In [157]:
# Create 3x3 matrix with random numbers (0 to 1)
f=np.random.random((3,3))
print(f)

[[0.56991294 0.77643254 0.53973457]
 [0.26152294 0.23894642 0.4601758 ]
 [0.10881951 0.15455908 0.04785196]]


In [158]:
# Create 1D array (112 to 120)
arr1=np.arange(112,121)
print(arr1)

[112 113 114 115 116 117 118 119 120]


In [159]:
# Replace 112 with 111 in 'arr1'
arr1[arr1 == 112] = 111
print(arr1)

[111 113 114 115 116 117 118 119 120]


In [160]:
# Attempt to replace numerical value with string 'csd' (will cause ValueError)
arr1[arr1==111]='csd'
print(arr1)

ValueError: invalid literal for int() with base 10: 'csd'

In [161]:
# Modify elements equal to 112, 113, or 114 by multiplying by 111
condition = (arr1 == 112) |(arr1==113)|(arr1 == 114)

arr1[condition] = arr1[condition] * 111

print(arr1)

[  111 12543 12654   115   116   117   118   119   120]


In [162]:
# Display the maximum value in 'arr1'
arr1.max()

np.int64(12654)

# NumPy from string, sets, and dictionary